models/Form1.php
<?php

namespace app\models;

use yii\base\Model;

class Form1 extends Model //descriptive post
{
    public $type;
    public $company_name;
    public $position;
    public $position_description;
    public $salary;
    public $starts_at;
    public $ends_at;
    public $post_at;

    public function rules()
    {
        return [
            [['type', 'company_name', 'position', 'ends_at'], 'required'],
            ['type', 'integer'],
            ['position_description', 'string'],
            ['salary', 'number', 'message' => 'Размер заработной платы должен быть числом'],
            [['starts_at', 'ends_at'], 'date', 'format' => 'php:Y-m-d', 'message' => 'Формат должен быть Y-m-d'],
            ['post_at', 'date', 'format' => 'php:Y-m-d H:i:s', 'message' => 'Формат должен быть Y-m-d H:i:s'],
            ['post_at', 'compare', 'compareValue' => date('Y-m-d H:i:s'), 'operator' => '>', 'type' => 'datetime'],
            ['starts_at', 'default', 'value' => date('Y-m-d')],
            ['post_at', 'default', 'value' => date('Y-m-d H:i:s')],
            ['ends_at', 'checkDateRange'],

            ];
    }

    public function attributeLabels()
    {
        return [
            'company_name' => 'Название компании',
            'position' => 'Должность',
            'position_description' => 'Описание должности',
            'salary' => 'Размер заработной платы',
            'starts_at' => 'Дата начала',
            'ends_at' => 'Дата окончания',
            'post_at' => 'Дата размещения'

        ];
    }

    public function checkDateRange($attribute, $params)
    {
        if (!($this->ends_at > date('Y-m-d', strtotime('+3 months', strtotime($this->starts_at))))) {
            $this->addError($attribute, 'минимальный период даты начала и даты окончания - 3 месяца');
        }
    }

}

models/Form2.php
<?php

namespace app\models;

use yii\base\Model;

class Form2 extends Model //contact post
{
    public $type;
    public $company_name;
    public $position;
    public $contact_name;
    public $contact_email;
    public $post_at;

    public function rules()
    {
        return [
            [['type', 'company_name', 'position', 'contact_email'], 'required'],
            ['type', 'integer'],
            ['contact_name', 'string'],
            ['contact_email', 'email'],
            ['post_at', 'date', 'format' => 'php:Y-m-d H:i:s', 'message' => 'Формат должен быть Y-m-d H:i:s'],
            ['post_at', 'compare', 'compareValue' => date('Y-m-d H:i:s'), 'operator' => '>', 'type' => 'datetime'],
            ['post_at', 'default', 'value' => date('Y-m-d  H:i:s')],
        ];
    }
    public function attributeLabels()
    {
        return [
            'company_name' => 'Название компании',
            'position' => 'Должность',
            'contact_name' => 'Контактное имя',
            'contact_email' => 'Контактный email',
            'post_at' => 'Дата размещения'

        ];
    }
}

controllers/AjaxController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use app\models\Form1;
use app\models\Form2;
use app\services\PostService;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotAcceptableHttpException;
use yii\web\Response;
use yii\web\UnauthorizedHttpException;
use yii\widgets\ActiveForm;

class AjaxController extends Controller
{
    public function actionIndex()
    {
        throw new HttpException(404);
    }

    public function actionForm1()
    {
        $form = new Form1();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            // данные в $form удачно проверены
            // запись данных с формы в бд
            // создание задания очереди, отправка письма на почту админу

            $postService = new PostService();
            $postService->runDescriptiveAction($form->getAttributes());

            Yii::$app->response->format = Response::FORMAT_JSON;

            return [
                'success' => true
            ];
        }
    }

    public function actionForm2()
    {
        $form = new Form2();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            // данные в $form удачно проверены
            // запись данных с формы в бд
            // создание задания очереди, отправка письма на почту админу

            $postService = new PostService();
            $postService->runContactAction($form->getAttributes());

            Yii::$app->response->format = Response::FORMAT_JSON;

            return [
                'success' => true
            ];
        }
    }

    public function actionValidationForm1()
    {
        $form1 = new Form1();
        if (Yii::$app->request->isAjax && $form1->load(Yii::$app->
            request->post())) {
            Yii::$app->response->format = 'json';

            return ActiveForm::validate($form1);
        }
    }

    public function actionValidationForm2()
    {
        $form2 = new Form2();
        if (Yii::$app->request->isAjax && $form2->load(Yii::$app->
            request->post())) {
            Yii::$app->response->format = 'json';

            return ActiveForm::validate($form2);
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\jobs\DescriptivePlacementApplicationJob;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Form1;
use app\models\Form2;
use yii\widgets\ActiveForm;
use app\services\PostService;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return Response|string
     */

    public function actionIndex()
    {
        $form1 = new Form1();
        $form2 = new Form2();

        // либо страница отображается первый раз, либо есть ошибка в данных

        return $this->render('index', [
            'form1' => $form1,
            'form2' => $form2
        ]);

    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php if (!empty($message)): ?>
        <div class="alert alert-danger">
            <?= nl2br(Html::encode($message)) ?>
        </div>
    <?php endif; ?>
    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/forms/form1.php
<?php

use app\jobs\DescriptivePlacementApplicationJob;
use app\models\Form1;
use kartik\datetime\DateTimePicker;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\entities\Post;

?>

<?php $activeForm = ActiveForm::begin([
    'id' => 'form1',
    'enableAjaxValidation' => true,
    'validationUrl' => Url::toRoute('ajax/validation-form1')
]); ?>
<?= $activeForm->field($formModel, 'type')->hiddenInput([
    'value' => Post::POST_TYPE_DESCRIPTIVE
])
    ->label(false); ?>
<?= $activeForm->field($formModel, 'company_name') ?>
<?= $activeForm->field($formModel, 'position') ?>
<?= $activeForm->field($formModel, 'position_description') ?>
<?= $activeForm->field($formModel, 'salary') ?>
<?= $activeForm->field($formModel, 'starts_at') ?>
<?= $activeForm->field($formModel, 'ends_at') ?>
<?= $activeForm->field($formModel, 'post_at')->widget(
    DateTimePicker::class,
    [
        'options' => ['placeholder' => $formModel->getAttributeLabel('post_at')],
        'convertFormat' => true,
        'pluginOptions' => [
            'format' => 'yyyy-MM-dd HH:mm:00',
            'startDate' => date('Y-m-d H:i:s'),
            'todayHighlight' => true
        ]
    ]
); ?>

    <div class="form-group">
        <?= Html::submitButton('Отправить', ['btn btn-primary']); ?>
    </div>

<?php ActiveForm::end();?>

    <div id="response1">
        <p>Данные успешно отправлены</p>
    </div>


<?php
$js = <<<JS
$('#response1').hide();
    $('#form1').on('beforeSubmit', function(){
       var data = $(this).serialize();
        $.ajax({
            url: '/ajax/form1',
            type: 'POST',
            data: data,
            success: function(response){
                $('#response1').fadeIn(500);  
                $('#form1').trigger("reset");
                $('#response1').fadeOut(15000);
                //console.log(response1);
            },
            error: function(){
                alert('Error!');
            }
        });
        return false;
    });
JS;
$this->registerJs($js);
?>

views/site/forms/form2.php
<?php

use kartik\datetime\DateTimePicker;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\entities\Post;

?>

<?php $activeForm = ActiveForm::begin([
    'id' => 'form2',
    'enableAjaxValidation' => true,
    'validationUrl' => Url::toRoute('ajax/validation-form2')
]); ?>
<?= $activeForm->field($formModel, 'type')->hiddenInput([
    'value' => Post::POST_TYPE_CONTACT
])
    ->label(false); ?>
<?= $activeForm->field($formModel, 'company_name') ?>
<?= $activeForm->field($formModel, 'position') ?>
<?= $activeForm->field($formModel, 'contact_name') ?>
<?= $activeForm->field($formModel, 'contact_email') ?>
<?= $activeForm->field($formModel, 'post_at')->widget(
    DateTimePicker::class,
    [
        'options' => ['placeholder' => $formModel->getAttributeLabel('post_at')],
        'convertFormat' => true,
        'pluginOptions' => [
            'format' => 'yyyy-MM-dd HH:mm:00',
            'startDate' => date('Y-m-d H:i:s'),
            'todayHighlight' => true
        ]
    ]
);?>

    <div class="form-group">
        <?= Html::submitButton('Отправить', ['btn btn-primary']); ?>
    </div>

<?php ActiveForm::end(); ?>

    <div id="response2">
        <p>Данные успешно отправлены</p>
    </div>


<?php
$js = <<<JS
$('#response2').hide();
    $('#form2').on('beforeSubmit', function(){
       var data = $(this).serialize();
        $.ajax({
            url: '/ajax/form2',
            type: 'POST',
            data: data,
            success: function(response){
                $('#response2').fadeIn(500);
                $('#form2').trigger("reset");
                $('#response2').fadeOut(15000);
                //console.log(res);
            },
            error: function(){
                alert('Error!');
            }
        });
        return false;
    });
JS;
$this->registerJs($js);
?>

views/site/index.php
<?php
use yii\bootstrap\Tabs;

?>
<?php
echo Tabs::widget([
    'items' => [

        [
            'label' => 'Тип формы',
            'items' => [
                [
                    'label' => 'форма1',
                    'content' => $this->render('forms/form1', ['formModel' => $form1]),
                    'active' => true
                ],
                [
                    'label' => 'форма2',
                    'content' => $this->render('forms/form2', ['formModel' => $form2])
                ],

            ]
        ]
    ]
]);
?>